name: Build and Deploy Docker Image
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
    setup-build-publish-deploy:
      name: Setup, Build, Publish, and Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@master
  
      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCLOUD_SERVICE_KEY }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCT_KEY }}
  
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
        
      # Build the Docker image
      - name: Build
        run: |        
          docker build . --tag gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/notify_dinner_flask
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/notify_dinner_flask
          
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud components install beta && gcloud beta run deploy ${{ secrets.SERVICE_NAME }} --quiet --image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/notify_dinner_flask --project ${{ secrets.GOOGLE_PROJECT_ID }} --region us-central1 --platform managed