name: Build and Deploy Docker Image
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Push image to GCR
        uses: RaccoonDev/push-docker-gcr@v1
        with:
          gcr_host: gcr.io
          image_name: notify_dinner_flask
          image_tag: latest
          env:
            GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
            GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}